WebAppCreditos/Controllers/DeclaracionImpController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Modelo.Entidades;
using ModeloDB;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebAppCreditos.Controllers
{
    public class DeclaracionImpController : Controller
    {
        private readonly DBCreditos db;

        public DeclaracionImpController(DBCreditos db)
        {
            this.db = db;
        }

        //Listar Rol Pagos
        public IActionResult Index()
        {
            IEnumerable<DeclaracionImp> listaDeclaracionImp = db.DeclaracionImps
                .Include(afiliado => afiliado.Solicitante);

            return View(listaDeclaracionImp);
        }

        [HttpGet]
        public IActionResult Create()
        {
            // Lista de Solicitantes
            var listaSoli = db.Solicitantes
                .Select(Soli => new
                {
                    SolicitanteId = Soli.SolicitanteId,
                    Nombres = Soli.Nombres,
                    Apellidos = Soli.Apellidos
                }).ToList();

            // Prepara las listas
            var selectListaSolicitantes = new SelectList(listaSoli, "SolicitanteId", "Nombres", "Apellidos");

            // Ingreso a ViewBag
            ViewBag.selectListSolicitantes = selectListaSolicitantes;

            return View();
        }

        [HttpPost]
        public IActionResult Create(DeclaracionImp declaracion)
        {
            //Total de Declaracion 
            declaracion.TotalIngresos = declaracion.VentasAnuales - (declaracion.AporteIESS + declaracion.PrestamosIESS + declaracion.GastosVarios);

            db.DeclaracionImps.Add(declaracion);
            db.SaveChanges();

            TempData["mensaje"] = $"La declaracion del solicitante {declaracion.SolicitanteId} se ha creado correctamente";

            return RedirectToAction("Index");
        }

        //Edicion de Declaracion
        //Presenta el formulario lleno con los datos del declaracion
        [HttpGet]
        public IActionResult Edit(int id)
        {
            // Lista de Solicitantes
            var listaSoli = db.Solicitantes
                .Select(Soli => new
                {
                    SolicitanteId = Soli.SolicitanteId,
                    Nombres = Soli.Nombres,
                    Apellidos = Soli.Apellidos
                }).ToList();

            // Prepara las listas
            var selectListaSolicitantes = new SelectList(listaSoli, "SolicitanteId", "Nombres", "Apellidos");

            // Ingreso a ViewBag
            ViewBag.selectListSolicitantes = selectListaSolicitantes;

            var declaracion = db.DeclaracionImps
               .Include(soli => soli.Solicitante)
               .Single(afili => afili.DeclaracionImpId == id);

            return View(declaracion);
        }

        //Actualiza declaracion
        [HttpPost]
        public IActionResult Edit(DeclaracionImp declaracion)
        {
            //Total de Declaracion 
            declaracion.TotalIngresos = declaracion.VentasAnuales - (declaracion.AporteIESS + declaracion.PrestamosIESS + declaracion.GastosVarios);

            db.DeclaracionImps.Update(declaracion);
            db.SaveChanges();

            TempData["mensaje"] = $"La declaracion del solicitante {declaracion.SolicitanteId} se ha editada correctamente";

            return RedirectToAction("Index");
        }

        //Eliminar Declaracion
        //Presenta el formulario lleno con los datos del Declraracion
        [HttpGet]
        public IActionResult Delete(int id)
        {
            // Lista de Solicitantes
            var listaSoli = db.Solicitantes
                .Select(Soli => new
                {
                    SolicitanteId = Soli.SolicitanteId,
                    Nombres = Soli.Nombres,
                    Apellidos = Soli.Apellidos
                }).ToList();

            // Prepara las listas
            var selectListaSolicitantes = new SelectList(listaSoli, "SolicitanteId", "Nombres", "Apellidos");

            // Ingreso a ViewBag
            ViewBag.selectListSolicitantes = selectListaSolicitantes;

            var declaracion = db.DeclaracionImps
               .Include(soli => soli.Solicitante)
               .Single(afili => afili.DeclaracionImpId == id);

            return View(declaracion);
        }

        //Confirmar eliminacion
        [HttpPost]
        public IActionResult Delete(DeclaracionImp declaracion)
        {
            db.DeclaracionImps.Remove(declaracion);
            db.SaveChanges();

            TempData["mensaje"] = $"El afiliado se ha eliminado correctamente";

            return RedirectToAction("Index");
        }
    }
}

WebAppCreditos/Views/DeclaracionImp/Create.cshtml
@using Modelo.Entidades
 
@model DeclaracionImp

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Creacion de la declaracion de impuestos</h1>

<div class="container">
    <div class="row">
        <div class="">
            <h3 class="text-center">Ingrese los datos de declaracion impuestos</h3>
        </div>
    </div>
    <div class="row">
        <div class="">
            <form method="post" asp-action="Create">
                <div class="form-group">
                    <label class="control-label">Solicitante</label>
                    <select class="form-control" asp-for="SolicitanteId" asp-items="@ViewBag.selectListSolicitantes">
                        <option value="">--Selecciona un Solicitante--</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="ventasanuales">Ingrese las ventas mensuales</label>
                    <input class="form-control" asp-for="VentasAnuales">
                </div>
                <div class="form-group">
                    <label for="aporteIess">Ingrese cuanto aporta al IESS por mes</label>
                    <input class="form-control" asp-for="AporteIESS">
                </div>
                <div class="form-group">
                    <label for="prestamoIess">Ingrese si paga algun prestamo al IESS</label>
                    <input class="form-control" asp-for="PrestamosIESS">
                </div>
                <div class="form-group">
                    <label for="Gastosvarios">Ingrese sus Gastos Varios</label>
                    <input class="form-control" asp-for="GastosVarios">
                </div>
                <div class="form-group">
                    <input class="btn btn-success" type="submit" value="Crear Declaracion" />
                </div>
            </form>
        </div>
    </div>
</div>

WebAppCreditos/Views/DeclaracionImp/Delete.cshtml
@using Modelo.Entidades

@model DeclaracionImp

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Borrar Declaracion</h1>

<div class="container">
    <div class="row">
        <div class="">
            <h3 class="text-center">Confirmacion borrar declaracion : @Model.Solicitante.Nombres @Model.Solicitante.Apellidos</h3>
        </div>
    </div>
    <div class="row">
        <div class="">
            <form method="post" asp-action="Delete">
                <input type="hidden" asp-for="DeclaracionImpId" />
                <div class="form-group">
                    <label class="control-label">Solicitante</label>
                    <select class="form-control" asp-for="SolicitanteId" asp-items="@ViewBag.selectListSolicitantes" disabled>
                        <option value="">--Selecciona un Solicitante--</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="ventasanuales">Ingrese las ventas anuales</label>
                    <input class="form-control" asp-for="VentasAnuales" disabled>
                </div>
                <div class="form-group">
                    <label for="aporteIess">Ingrese cuanto aporta al IESS por mes</label>
                    <input class="form-control" asp-for="AporteIESS" disabled>
                </div>
                <div class="form-group">
                    <label for="prestamoIess">Ingrese si paga algun prestamo al IESS</label>
                    <input class="form-control" asp-for="PrestamosIESS" disabled>
                </div>
                <div class="form-group">
                    <label for="Gastosvarios">Ingrese sus Gastos Varios</label>
                    <input class="form-control" asp-for="GastosVarios" disabled>
                </div>
                <div class="form-group">
                    <label for="totalIngresos">Ingrese sus Ingresos Totales</label>
                    <input class="form-control" asp-for="TotalIngresos" disabled>
                </div>
                <div class="form-group">
                    <input class="btn btn-success" type="submit" value="Eliminar" />
                </div>
            </form>
        </div>
    </div>
</div>

WebAppCreditos/Views/DeclaracionImp/Edit.cshtml
@using Modelo.Entidades

@model DeclaracionImp

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Actualizar Declaracion Impuestos</h1>

<div class="container">
    <div class="row">
        <div class="">
            <h3 class="text-center">Editar la declaracion del solicitante : @Model.Solicitante.Nombres @Model.Solicitante.Apellidos</h3>
        </div>
    </div>
    <div class="row">
        <div class="">
            <form method="post" asp-action="Edit">
                <input type="hidden" asp-for="DeclaracionImpId" />
                <div class="form-group">
                    <label class="control-label">Solicitante</label>
                    <select class="form-control" asp-for="SolicitanteId" asp-items="@ViewBag.selectListSolicitantes">
                        <option value="">--Selecciona un Solicitante--</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="ventasanuales">Ingrese las ventas mensuales</label>
                    <input class="form-control" asp-for="VentasAnuales">
                </div>
                <div class="form-group">
                    <label for="aporteIess">Ingrese cuanto aporta al IESS por mes</label>
                    <input class="form-control" asp-for="AporteIESS">
                </div>
                <div class="form-group">
                    <label for="prestamoIess">Ingrese si paga algun prestamo al IESS</label>
                    <input class="form-control" asp-for="PrestamosIESS">
                </div>
                <div class="form-group">
                    <label for="Gastosvarios">Ingrese sus Gastos Varios</label>
                    <input class="form-control" asp-for="GastosVarios">
                </div>
                <div class="form-group">
                    <input class="btn btn-success" type="submit" value="Editar" />
                </div>
            </form>
        </div>
    </div>
</div>

WebAppCreditos/Views/DeclaracionImp/Index.cshtml
@using Modelo.Entidades

@model IEnumerable<DeclaracionImp>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Lista Declaracion Impuestos</h1>
<p> A continución se presenta la lista de las Declaraciones de Impuestos del Sistema de Aprovación de Créditos BIESS</p>

<div class="container">
    <div class="row">
        <div class="col-sm-6">
            <h3>Declaracion</h3>
        </div>
        <div class="col-sm-6">
            <a class="btn btn-success d-block" asp-controller="DeclaracionImp" asp-action="Create">
                Nuevo Declaracion
            </a>
        </div>
    </div>
    @if (TempData["mensaje"] != null)
    {
        <div class="alert alert-warning alert-dismissible fade show " role="alert">
            @TempData["mensaje"]
            <button type="button" class="close" data-dismiss="alert" aria-label="close">
                <span ariaaria-hidden="true">
                    &times;
                </span>
            </button>
        </div>
    }
    <div class="row">
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Ventas Anuales</th>
                    <th>Aporte IESS</th>
                    <th>Prestamos IESS</th>
                    <th>Gastos Varios</th>
                    <th>Total Ingresos</th>
                    <th>Solicitante</th>
                </tr>
            </thead>
            <tbody>
                @foreach (DeclaracionImp declaracion in Model)
                {
                <tr>
                    <td>@declaracion.DeclaracionImpId</td>
                    <td>@declaracion.VentasAnuales</td>
                    <td>@declaracion.AporteIESS</td>
                    <td>@declaracion.PrestamosIESS</td>
                    <td>@declaracion.GastosVarios</td>
                    <td>@declaracion.TotalIngresos</td>
                    <td>@declaracion.Solicitante.Nombres @declaracion.Solicitante.Apellidos</td>
                    <td>
                        <a class="btn btn-warning" asp-controller="DeclaracionImp" asp-action="Edit" asp-route-id="@declaracion.DeclaracionImpId"> Editar </a>
                        <a class="btn btn-danger" asp-controller="DeclaracionImp" asp-action="Delete" asp-route-id="@declaracion.DeclaracionImpId"> Eliminar </a>
                    </td>
                </tr>
                }
            </tbody>
        </table>
    </div>
</div>
