WebAppCreditos/Controllers/SolicitudController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Modelo.Entidades;
using ModeloDB;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebAppCreditos.Controllers
{
    public class SolicitudController : Controller
    {
        private readonly DBCreditos db;

        public SolicitudController(DBCreditos db)
        {
            this.db = db;
        }

        //Listar Solicitud
        public IActionResult Index()
        {
            IEnumerable<Solicitud> listaSolicitud = db.Solicitud
                .Include(afi => afi.Afiliado)
                    .ThenInclude(soli => soli.Solicitante);

            return View(listaSolicitud);
        }

        [HttpGet]
        public IActionResult Create()
        {
            // Lista de Afiliados
            var listaAfiliado = db.Afiliado
                .Include(sol => sol.Solicitante)
                .Select(afi => new
                {
                    AfiliadoId = afi.AfiliadoId,
                    Nombres = afi.Solicitante.Nombres,
                    Apellidos = afi.Solicitante.Apellidos
                }).ToList();
            // Lista de Detalle CapcidadPagos
            var listaCap = db.CapacidadPagos
                .Include(ga => ga.Gastos)
                    .ThenInclude(sol => sol.Solicitante)
                .Select(cap => new
                {
                    CapacidadId = cap.CapacidadPagoId,
                    Nombres = cap.Gastos.Solicitante.Nombres,
                    Apellidos = cap.Gastos.Solicitante.Apellidos
                }).ToList();
            // Lista de Detalle BienAdquirir
            var listaBien = db.BienAdquirirs
                .Select(bien => new
                {
                    BienId = bien.BienAdquirirId,
                    Nombres = bien.Propietario
                }).ToList();
            // Lista de Detalle Historial Crediticio
            var listaHistorial = db.HistorialCrediticios
                .Include(bien => bien.BienesSolicitante)
                    .ThenInclude(sol => sol.Solicitante)
                .Select(dets => new
                {
                    HistorialId = dets.HistorialCrediticioId,
                    Nombres = dets.BienesSolicitante.Solicitante.Nombres,
                    Apellidos = dets.BienesSolicitante.Solicitante.Apellidos
                }).ToList();

            // Prepara las listas
            var selectListaAfiliado = new SelectList(listaAfiliado, "AfiliadoId", "Nombres", "Apellidos");
            var selectListaCap = new SelectList(listaCap, "CapacidadId", "Nombres", "Apellidos");
            var selectListaBien = new SelectList(listaBien, "BienId", "Nombres");
            var selectListaHistorial = new SelectList(listaHistorial, "HistorialId", "Nombres", "Apellidos");

            // Ingreso a ViewBag
            ViewBag.selectListAfiliado = selectListaAfiliado;
            ViewBag.selectListCap = selectListaCap;
            ViewBag.selectListBien = selectListaBien;
            ViewBag.selectListHistorial = selectListaHistorial;

            return View();
        }

        [HttpPost]
        public IActionResult Create(Solicitud soli)
        {
            //Consulta Tipo Credito
            var tmpadquirr = db.BienAdquirirs
                .Single(add => add.BienAdquirirId == soli.BienAdquirirId);

            soli.TipoCredito = tmpadquirr.TipoVivienda;
            soli.TotalCredito = tmpadquirr.Avaluo;

            // Consulta Solicitante
            var tmpSoli = db.Afiliado
                .Include(soli => soli.Solicitante)
                .Single(afi => afi.AfiliadoId == soli.AfiliadoId);

            soli.DiscapacidadDesc = tmpSoli.Solicitante.Discapacidad;

            //Caclulo tiempo de pago
            soli.NumeroPagos = soli.TiempoCredito * 12;

            //Calculo Cuota mensual
            double mensual = (soli.TotalCredito * 0.067)/12;
            soli.CuotaMensual = (float)mensual;

            //Caculo Cuota Mensual Total
            soli.TotalCuota = soli.CuotaDesgrav + soli.CuotaMensual + soli.CuatoSeguro;

            db.Solicitud.Add(soli);
            db.SaveChanges();

            TempData["mensaje"] = $"La Solicitud se ha creado correctamente";

            return RedirectToAction("Index");
        }

        //Edicion de BieneSolicitante
        //Presenta el formulario lleno con los datos del Bien
        [HttpGet]
        public IActionResult Edit(int id)
        {
            // Lista de Afiliados
            var listaAfiliado = db.Afiliado
                .Include(sol => sol.Solicitante)
                .Select(afi => new
                {
                    AfiliadoId = afi.AfiliadoId,
                    Nombres = afi.Solicitante.Nombres,
                    Apellidos = afi.Solicitante.Apellidos
                }).ToList();
            // Lista de Detalle CapcidadPagos
            var listaCap = db.CapacidadPagos
                .Include(sol => sol.Gastos)
                    .ThenInclude(sol => sol.Solicitante)
                .Select(cap => new
                {
                    CapacidadId = cap.CapacidadPagoId,
                    Nombres = cap.Gastos.Solicitante.Nombres,
                    Apellidos = cap.Gastos.Solicitante.Apellidos
                }).ToList();
            // Lista de Detalle BienAdquirir
            var listaBien = db.BienAdquirirs
                .Select(bien => new
                {
                    BienId = bien.BienAdquirirId,
                    Nombres = bien.Propietario
                }).ToList();
            // Lista de Detalle Historial Crediticio
            var listaHistorial = db.HistorialCrediticios
                .Include(bien => bien.BienesSolicitante)
                    .ThenInclude(sol => sol.Solicitante)
                .Select(dets => new
                {
                    HistorialId = dets.HistorialCrediticioId,
                    Nombres = dets.BienesSolicitante.Solicitante.Nombres,
                    Apellidos = dets.BienesSolicitante.Solicitante.Apellidos
                }).ToList();

            // Prepara las listas
            var selectListaAfiliado = new SelectList(listaAfiliado, "AfiliadoId", "Nombres", "Apellidos");
            var selectListaCap = new SelectList(listaCap, "CapacidadId", "Nombres", "Apellidos");
            var selectListaBien = new SelectList(listaBien, "BienId", "Nombres");
            var selectListaHistorial = new SelectList(listaHistorial, "HistorialId", "Nombres", "Apellidos");

            // Ingreso a ViewBag
            ViewBag.selectListAfiliado = selectListaAfiliado;
            ViewBag.selectListCap = selectListaCap;
            ViewBag.selectListBien = selectListaBien;
            ViewBag.selectListHistorial = selectListaHistorial;

            var solicitud = db.Solicitud
                .Include(rol => rol.Afiliado)
                    .ThenInclude(sol => sol.Solicitante)
                .Single(afili => afili.SolicitudId == id);

            return View(solicitud);
        }

        //Actualiza BienSolicitante
        [HttpPost]
        public IActionResult Edit(Solicitud soli)
        {
            db.Solicitud.Update(soli);
            db.SaveChanges();

            TempData["mensaje"] = $"La solicitud se ha editado correctamente";

            return RedirectToAction("Index");
        }

        //Eliminar Bien
        //Presenta el formulario lleno con los datos del bien seleccionado
        [HttpGet]
        public IActionResult Delete(int id)
        {
            // Lista de Afiliados
            var listaAfiliado = db.Afiliado
                .Include(sol => sol.Solicitante)
                .Select(afi => new
                {
                    AfiliadoId = afi.AfiliadoId,
                    Nombres = afi.Solicitante.Nombres,
                    Apellidos = afi.Solicitante.Apellidos
                }).ToList();
            // Lista de Detalle CapcidadPagos
            var listaCap = db.CapacidadPagos
                .Include(sol => sol.Gastos)
                    .ThenInclude(sol => sol.Solicitante)
                .Select(cap => new
                {
                    CapacidadId = cap.CapacidadPagoId,
                    Nombres = cap.Gastos.Solicitante.Nombres,
                    Apellidos = cap.Gastos.Solicitante.Apellidos
                }).ToList();
            // Lista de Detalle BienAdquirir
            var listaBien = db.BienAdquirirs
                .Select(bien => new
                {
                    BienId = bien.BienAdquirirId,
                    Nombres = bien.Propietario
                }).ToList();
            // Lista de Detalle Historial Crediticio
            var listaHistorial = db.HistorialCrediticios
                .Include(bien => bien.BienesSolicitante)
                    .ThenInclude(sol => sol.Solicitante)
                .Select(dets => new
                {
                    HistorialId = dets.HistorialCrediticioId,
                    Nombres = dets.BienesSolicitante.Solicitante.Nombres,
                    Apellidos = dets.BienesSolicitante.Solicitante.Apellidos
                }).ToList();

            // Prepara las listas
            var selectListaAfiliado = new SelectList(listaAfiliado, "AfiliadoId", "Nombres", "Apellidos");
            var selectListaCap = new SelectList(listaCap, "CapacidadId", "Nombres", "Apellidos");
            var selectListaBien = new SelectList(listaBien, "BienId", "Nombres");
            var selectListaHistorial = new SelectList(listaHistorial, "HistorialId", "Nombres", "Apellidos");

            // Ingreso a ViewBag

WebAppCreditos/Views/Solicitud/Create.cshtml
@using Modelo.Entidades
 
@model Solicitud

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Creacion de la Solicitud</h1>

<div class="container">
    <div class="row">
        <div class="">
            <h3 class="text-center">Ingrese los datos de la Solicitud</h3>
        </div>
    </div>
    <div class="row">
        <div class="">
            <form method="post" asp-action="Create">
                <div class="form-group">
                    <label class="control-label">Tiempo de pago en años</label>
                    <input class="form-group" asp-for="TiempoCredito" />
                </div>
                <div class="form-group">
                    <label class="control-label">Tasa Nominal Anual</label>
                    <input class="form-group" asp-for="TNA" value="6,70" />
                </div>
                <div class="form-group">
                    <label class="control-label">Cuota Desgravamen</label>
                    <input class="form-group" asp-for="CuotaDesgrav" value="21,13"  />
                </div>
                <div class="form-group">
                    <label class="control-label">Cuota del Seguro</label>
                    <input class="form-group" asp-for="CuatoSeguro" value="6,93" />
                </div>
                <div class="form-group">
                    <label class="control-label">Bienes Solicitante</label>
                    <select class="form-control" asp-for="BienAdquirirId" asp-items="@ViewBag.selectListBien">
                        <option value="">--Selecciona--</option>
                    </select>
                </div>
                <div class="form-group">
                    <label class="control-label">Afiliado</label>
                    <select class="form-control" asp-for="AfiliadoId" asp-items="@ViewBag.selectListAfiliado">
                        <option value="">--Selecciona--</option>
                    </select>
                </div>
                <div class="form-group">
                    <label class="control-label">Historial Crediticio</label>
                    <select class="form-control" asp-for="HistorialCrediticioId" asp-items="@ViewBag.selectListHistorial">
                        <option value="">--Selecciona--</option>
                    </select>
                </div>
                <div class="form-group">
                    <label class="control-label">Capcidad Pago</label>
                    <select class="form-control" asp-for="CapacidadPagoId" asp-items="@ViewBag.selectListCap">
                        <option value="">--Selecciona--</option>
                    </select>
                </div>
                <div class="form-group">
                    <input class="btn btn-success" type="submit" value="Crear Bien" />
                </div>
            </form>
        </div>
    </div>
</div>

WebAppCreditos/Views/Solicitud/Delete.cshtml
@using Modelo.Entidades

@model Solicitud

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Borrar la Solicitud</h1>

<div class="container">
    <div class="row">
        <div class="">
            <h3 class="text-center"> Eliminar la Solicitud del solicitante : @Model.Afiliado.Solicitante.Nombres @Model.Afiliado.Solicitante.Apellidos</h3>
        </div>
    </div>
    <div class="row">
        <div class="">
            <form method="post" asp-action="Delete">
                <input type="hidden" asp-for="SolicitudId" />
                <div class="form-group">
                    <label class="control-label">Tipo de Crédito</label>
                    <select class="form-control" asp-for="TipoCredito" disabled>
                        <option value="">--Selecciona--</option>
                        <option value="VIVIENDA DE INTERÉS PÚBLICO">VIVIENDA DE INTÉRES PÚBLICO</option>
                        <option value="VIVIENDA TERMINADA">VIVIENDA TERMINADA</option>
                        <option value="OTROS INMUEBLES">OTROS INMUEBLES</option>
                        <option value="TERRENO">TERRENO</option>
                    </select>
                </div>
                <div class="form-group">
                    <label class="control-label">Descuento Discapacidad</label>
                    <select class="form-control" asp-for="DiscapacidadDesc" disabled>
                        <option value="">--Selecciona--</option>
                        <option value="true">Si</option>
                        <option value="false">No</option>
                    </select>
                </div>
                <div class="form-group">
                    <label class="control-label">Tasa Nominal Anual</label>
                    <input class="form-group" asp-for="TNA" value="6,70" disabled />
                </div>
                <div class="form-group">
                    <label class="control-label">Total Crédito</label>
                    <input class="form-group" asp-for="TotalCredito" disabled/>
                </div>
                <div class="form-group">
                    <label class="control-label">Número de Pagos</label>
                    <input class="form-group" asp-for="NumeroPagos" disabled/>
                </div>
                <div class="form-group">
                    <label class="control-label">Cuota Desgravamen</label>
                    <input class="form-group" asp-for="CuotaDesgrav" value="21,13" disabled />
                </div>
                <div class="form-group">
                    <label class="control-label">Cuota del Seguro</label>
                    <input class="form-group" asp-for="CuatoSeguro" value="6,93" disabled />
                </div>
                <div class="form-group">
                    <label class="control-label">Cuota Mensual</label>
                    <input class="form-group" asp-for="CuotaMensual" disabled/>
                </div>
                <div class="form-group">
                    <label class="control-label">Bienes Solicitante</label>
                    <select class="form-control" asp-for="BienAdquirirId" asp-items="@ViewBag.selectListBien" disabled>
                        <option value="">--Selecciona--</option>
                    </select>
                </div>
                <div class="form-group">
                    <label class="control-label">Bienes Solicitante</label>
                    <select class="form-control" asp-for="AfiliadoId" asp-items="@ViewBag.selectListAfiliado" disabled>
                        <option value="">--Selecciona--</option>
                    </select>
                </div>
                <div class="form-group">
                    <label class="control-label">Bienes Solicitante</label>
                    <select class="form-control" asp-for="HistorialCrediticioId" asp-items="@ViewBag.selectListHistorial" disabled>
                        <option value="">--Selecciona--</option>
                    </select>
                </div>
                <div class="form-group">
                    <label class="control-label">Bienes Solicitante</label>
                    <select class="form-control" asp-for="CapacidadPagoId" asp-items="@ViewBag.selectListCap" disabled>
                        <option value="">--Selecciona--</option>
                    </select>
                </div>
                <div class="form-group">
                    <label class="control-label">Total Mensual a Pagar</label>
                    <input class="form-group" asp-for="TotalCuota" disabled/>
                </div>
                <div class="form-group">
                    <input class="btn btn-success" type="submit" value="Eliminar" />
                </div>
            </form>
        </div>
    </div>
</div>

WebAppCreditos/Views/Solicitud/Edit.cshtml
@using Modelo.Entidades

@model Solicitud

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Actualizar la Solicitud</h1>

<div class="container">
    <div class="row">
        <div class="">
            <h3 class="text-center">Editar la Solicitud del solicitante : @Model.Afiliado.Solicitante.Nombres @Model.Afiliado.Solicitante.Apellidos</h3>
        </div>
    </div>
    <div class="row">
        <div class="">
            <form method="post" asp-action="Edit">
                <input type="hidden" asp-for="SolicitudId" />
                <div class="form-group">
                    <label class="control-label">Tiempo de pagos en años</label>
                    <input class="form-group" asp-for="TiempoCredito" />
                </div>
                <div class="form-group">
                    <label class="control-label">Tasa Nominal Anual</label>
                    <input class="form-group" asp-for="TNA" value="6,70"  />
                </div>
                <div class="form-group">
                    <label class="control-label">Cuota Desgravamen</label>
                    <input class="form-group" asp-for="CuotaDesgrav" value="21,13"  />
                </div>
                <div class="form-group">
                    <label class="control-label">Cuota del Seguro</label>
                    <input class="form-group" asp-for="CuatoSeguro" value="6,93"  />
                </div>
                <div class="form-group">
                    <label class="control-label">Bienes Solicitante</label>
                    <select class="form-control" asp-for="BienAdquirirId" asp-items="@ViewBag.selectListBien">
                        <option value="">--Selecciona--</option>
                    </select>
                </div>
                <div class="form-group">
                    <label class="control-label">Bienes Solicitante</label>
                    <select class="form-control" asp-for="AfiliadoId" asp-items="@ViewBag.selectListAfiliado">
                        <option value="">--Selecciona--</option>
                    </select>
                </div>
                <div class="form-group">
                    <label class="control-label">Bienes Solicitante</label>
                    <select class="form-control" asp-for="HistorialCrediticioId" asp-items="@ViewBag.selectListHistorial">
                        <option value="">--Selecciona--</option>
                    </select>
                </div>
                <div class="form-group">
                    <label class="control-label">Bienes Solicitante</label>
                    <select class="form-control" asp-for="CapacidadPagoId" asp-items="@ViewBag.selectListCap">
                        <option value="">--Selecciona--</option>
                    </select>
                </div>
                <div class="form-group">
                    <input class="btn btn-success" type="submit" value="Editar" />
                </div>
            </form>
        </div>
    </div>
</div>

WebAppCreditos/Views/Solicitud/Index.cshtml
@using Modelo.Entidades

@model IEnumerable<Solicitud>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Lista Solicitud</h1>
<p> A continución se presenta la lista de las Solicitudes del Sistema de Aprovación de Créditos BIESS</p>

<div class="container">
    <div class="row">
        <div class="col-sm-6">
            <h3>Solicitud</h3>
        </div>
        <div class="col-sm-6">
            <a class="btn btn-success d-block" asp-controller="Solicitud" asp-action="Create">
                Nueva Solicitud
            </a>
        </div>
    </div>
    @if (TempData["mensaje"] != null)
    {
        <div class="alert alert-warning alert-dismissible fade show " role="alert">
            @TempData["mensaje"]
            <button type="button" class="close" data-dismiss="alert" aria-label="close">
                <span ariaaria-hidden="true">
                    &times;
                </span>
            </button>
        </div>
    }
    <div class="row">
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Solicitante</th>
                    <th>Tipo Credito</th>
                    <th>Descuanto Discap</th>
                    <th>TNA</th>
                    <th>Tiempo Credito</th>
                    <th>Numero Pagos</th>
                    <th>Total Credito</th>
                    <th>Cuota Desgravamen</th>
                    <th>Cuota Seguro</th>
                    <th>Cuota Mensual</th>
                    <th>Total Cuota</th>
                </tr>
            </thead>
            <tbody>
                @foreach (Solicitud solicitud in Model)
                {
                <tr>
                    <td>@solicitud.SolicitudId</td>
                    <td>@solicitud.Afiliado.Solicitante.Nombres @solicitud.Afiliado.Solicitante.Apellidos</td>
                    <td>@solicitud.TipoCredito</td>
                    <td>@solicitud.DiscapacidadDesc</td>
                    <td>@solicitud.TNA</td>
                    <td>@solicitud.TiempoCredito</td>
                    <td>@solicitud.NumeroPagos</td>
                    <td>@solicitud.TotalCredito</td>
                    <td>@solicitud.CuotaDesgrav</td>
                    <td>@solicitud.CuatoSeguro</td>
                    <td>@solicitud.CuotaMensual</td>
                    <td>@solicitud.TotalCuota</td>
                    <td>
                        <a class="btn btn-warning" asp-controller="Solicitud" asp-action="Edit" asp-route-id="@solicitud.SolicitudId"> Editar </a>
                        <a class="btn btn-danger" asp-controller="Solicitud" asp-action="Delete" asp-route-id="@solicitud.SolicitudId"> Eliminar </a>
                    </td>
                </tr>
                }
            </tbody>
        </table>
    </div>
</div>
