WebAppCreditos/Controllers/BienesSolicitanteController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Modelo.Entidades;
using ModeloDB;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebAppCreditos.Controllers
{
    public class BienesSolicitanteController : Controller
    {
        private readonly DBCreditos db;

        public BienesSolicitanteController(DBCreditos db)
        {
            this.db = db;
        }

        //Listar Afiliados
        public IActionResult Index()
        {
            IEnumerable<BienesSolicitante> listaBienesSolicitante = db.BienesSolicitante
                .Include(afiliado => afiliado.Solicitante); 

            return View(listaBienesSolicitante);
        }

        [HttpGet]
        public IActionResult Create()
        {
            // Lista de Solicitantes
            var listaSoli = db.Solicitantes
                .Select(Soli => new
                {
                    SolicitanteId = Soli.SolicitanteId,
                    Nombres = Soli.Nombres,
                    Apellidos = Soli.Apellidos
                }).ToList();

            // Prepara las listas
            var selectListaSolicitantes = new SelectList(listaSoli, "SolicitanteId", "Nombres", "Apellidos");

            // Ingreso a ViewBag
            ViewBag.selectListSolicitantes = selectListaSolicitantes;

            return View();
        }

        [HttpPost]
        public IActionResult Create(BienesSolicitante bienes)
        {
            //Calculo total deudas bienes
            bienes.TotalPendienteBienes = bienes.PagoPendienteAutomovil + bienes.PagoPendienteCasa + bienes.PagoPendienteTerreno;

            db.BienesSolicitante.Add(bienes);
            db.SaveChanges();

            TempData["mensaje"] = $"El bien del solicitante {bienes.SolicitanteId} se ha creado correctamente";

            return RedirectToAction("Index");
        }

        //Edicion de BieneSolicitante
        //Presenta el formulario lleno con los datos del Bien
        [HttpGet]
        public IActionResult Edit(int id)
        {
            // Lista de Solicitantes
            var listaSoli = db.Solicitantes
                .Select(Soli => new
                {
                    SolicitanteId = Soli.SolicitanteId,
                    Nombres = Soli.Nombres,
                    Apellidos = Soli.Apellidos
                }).ToList();

            // Prepara las listas
            var selectListaSolicitantes = new SelectList(listaSoli, "SolicitanteId", "Nombres", "Apellidos");

            // Ingreso a ViewBag
            ViewBag.selectListSolicitantes = selectListaSolicitantes;

            var bienSolicitante = db.BienesSolicitante
                .Include(soli => soli.Solicitante)
                .Single(afili => afili.BienesSolicitanteId == id);

            return View(bienSolicitante);
        }

        //Actualiza BienSolicitante
        [HttpPost]
        public IActionResult Edit(BienesSolicitante bienes)
        {
            //Calculo total deudas bienes
            bienes.TotalPendienteBienes = bienes.PagoPendienteAutomovil + bienes.PagoPendienteCasa + bienes.PagoPendienteTerreno;

            db.BienesSolicitante.Update(bienes);
            db.SaveChanges();

            TempData["mensaje"] = $"El bien del solicitante  {bienes.SolicitanteId} se ha editado correctamente";

            return RedirectToAction("Index");
        }

        //Eliminar Bien
        //Presenta el formulario lleno con los datos del bien seleccionado
        [HttpGet]
        public IActionResult Delete(int id)
        {
            // Lista de Solicitantes
            var listaSoli = db.Solicitantes
                .Select(Soli => new
                {
                    SolicitanteId = Soli.SolicitanteId,
                    Nombres = Soli.Nombres,
                    Apellidos = Soli.Apellidos
                }).ToList();

            // Prepara las listas
            var selectListaSolicitantes = new SelectList(listaSoli, "SolicitanteId", "Nombres", "Apellidos");

            // Ingreso a ViewBag
            ViewBag.selectListSolicitantes = selectListaSolicitantes;

            var bienSolicitante = db.BienesSolicitante
                .Include(soli => soli.Solicitante)
                .Single(afili => afili.BienesSolicitanteId == id);

            return View(bienSolicitante);
        }

        //Confirmar eliminacion
        [HttpPost]
        public IActionResult Delete(BienesSolicitante bienes)
        {
            db.BienesSolicitante.Remove(bienes);
            db.SaveChanges();

            TempData["mensaje"] = $"El Bien se ha eliminado correctamente";

            return RedirectToAction("Index");
        }
    }
}

WebAppCreditos/Views/BienesSolicitante/Create.cshtml
@using Modelo.Entidades
 
@model BienesSolicitante

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Creacion del Bien</h1>

<div class="container">
    <div class="row">
        <div class="">
            <h3 class="text-center">Ingrese los datos del Bien</h3>
        </div>
    </div>
    <div class="row">
        <div class="">
            <form method="post" asp-action="Create">
                <div class="form-group">
                    <label class="control-label">Solicitante</label>
                    <select class="form-control" asp-for="SolicitanteId" asp-items="@ViewBag.selectListSolicitantes">
                        <option value="">--Selecciona un Solicitante--</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="automovil">¿Cuenta con automóvil?</label>
                    <select class="form-control" asp-for="Automovil" asp-items="Html.GetEnumSelectList<Automovil>()">
                        <option value="">--Selecciona un Solicitante--</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="pagopendienteautomovil">¿Cuenta con algun pago pendiente del Automóvil?</label>
                    <input class="form-control" asp-for="PagoPendienteAutomovil">
                </div>
                <div class="form-group">
                    <label for="casa">¿Cuenta con una Casa?</label>
                    <select class="form-control" asp-for="Casa" asp-items="Html.GetEnumSelectList<Casa>()">
                        <option value="">--Selecciona un Solicitante--</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="pagopendientecasa">¿Cuenta con algun pago pendiente de la casa?</label>
                    <input class="form-control" asp-for="PagoPendienteCasa">
                </div>
                <div class="form-group">
                    <label for="Terreno">¿Cuenta con un Terreno?</label>
                    <select class="form-control" asp-for="Terreno" asp-items="Html.GetEnumSelectList<Terreno>()">
                        <option value="">--Selecciona un Solicitante--</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="pagopendienteterreno">¿Cuenta con algun pago pendiente de la Terreno?</label>
                    <input class="form-control" asp-for="PagoPendienteTerreno">
                </div>
                <div class="form-group">
                    <input class="btn btn-success" type="submit" value="Crear Bien" />
                </div>
            </form>
        </div>
    </div>
</div>

WebAppCreditos/Views/BienesSolicitante/Delete.cshtml
@using Modelo.Entidades

@model BienesSolicitante

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Borrar Bien</h1>

<div class="container">
    <div class="row">
        <div class="">
            <h3 class="text-center">Confirmacion borrar Bien : @Model.Solicitante.Nombres @Model.Solicitante.Apellidos</h3>
        </div>
    </div>
    <div class="row">
        <div class="">
            <form method="post" asp-action="Delete">
                <input type="hidden" asp-for="BienesSolicitanteId" />
                <div class="form-group">
                    <label class="control-label">Solicitante</label>
                    <select class="form-control" asp-for="SolicitanteId" asp-items="@ViewBag.selectListSolicitantes" disabled>
                        <option value="">--Selecciona un Solicitante--</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="automovil">¿Cuenta con automóvil?</label>
                    <select class="form-control" asp-for="Automovil" asp-items="Html.GetEnumSelectList<Automovil>()" disabled>
                        <option value="">--Selecciona un Solicitante--</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="pagopendienteautomovil">¿Cuenta con algun pago pendiente del Automóvil?</label>
                    <input class="form-control" asp-for="PagoPendienteAutomovil" disabled>
                </div>
                <div class="form-group">
                    <label for="casa">¿Cuenta con una Casa?</label>
                    <select class="form-control" asp-for="Casa" asp-items="Html.GetEnumSelectList<Casa>()" disabled>
                        <option value="">--Selecciona un Solicitante--</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="pagopendientecasa">¿Cuenta con algun pago pendiente de la casa?</label>
                    <input class="form-control" asp-for="PagoPendienteCasa" disabled>
                </div>
                <div class="form-group">
                    <label for="Terreno">¿Cuenta con un Terreno?</label>
                    <select class="form-control" asp-for="Terreno" asp-items="Html.GetEnumSelectList<Terreno>()" disabled>
                        <option value="">--Selecciona un Solicitante--</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="pagopendienteterreno">¿Cuenta con algun pago pendiente de la Terreno?</label>
                    <input class="form-control" asp-for="PagoPendienteTerreno" disabled>
                </div>
                <div class="form-group">
                    <label for="TotalPendientes">Total Pago Pendientes</label>
                    <input class="form-control" asp-for="TotalPendienteBienes" disabled>
                </div>
                <div class="form-group">
                    <input class="btn btn-success" type="submit" value="Eliminar" />
                </div>
            </form>
        </div>
    </div>
</div>

WebAppCreditos/Views/BienesSolicitante/Edit.cshtml
@using Modelo.Entidades

@model BienesSolicitante

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Actualizar Bien Solicitante</h1>

<div class="container">
    <div class="row">
        <div class="">
            <h3 class="text-center">Editar del bien del solicitante : @Model.Solicitante.Nombres @Model.Solicitante.Apellidos</h3>
        </div>
    </div>
    <div class="row">
        <div class="">
            <form method="post" asp-action="Edit">
                <input type="hidden" asp-for="BienesSolicitanteId" />
                <div class="form-group">
                    <label class="control-label">Solicitante</label>
                    <select class="form-control" asp-for="SolicitanteId" asp-items="@ViewBag.selectListSolicitantes">
                        <option value="">--Selecciona un Solicitante--</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="automovil">¿Cuenta con automóvil?</label>
                    <select class="form-control" asp-for="Automovil" asp-items="Html.GetEnumSelectList<Automovil>()">
                        <option value="">--Selecciona un Solicitante--</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="pagopendienteautomovil">¿Cuenta con algun pago pendiente del Automóvil?</label>
                    <input class="form-control" asp-for="PagoPendienteAutomovil">
                </div>
                <div class="form-group">
                    <label for="casa">¿Cuenta con una Casa?</label>
                    <select class="form-control" asp-for="Casa" asp-items="Html.GetEnumSelectList<Casa>()">
                        <option value="">--Selecciona un Solicitante--</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="pagopendientecasa">¿Cuenta con algun pago pendiente de la casa?</label>
                    <input class="form-control" asp-for="PagoPendienteCasa">
                </div>
                <div class="form-group">
                    <label for="Terreno">¿Cuenta con un Terreno?</label>
                    <select class="form-control" asp-for="Terreno" asp-items="Html.GetEnumSelectList<Terreno>()">
                        <option value="">--Selecciona un Solicitante--</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="pagopendienteterreno">¿Cuenta con algun pago pendiente de la Terreno?</label>
                    <input class="form-control" asp-for="PagoPendienteTerreno">
                </div>
                <div class="form-group">
                    <input class="btn btn-success" type="submit" value="Editar" />
                </div>
            </form>
        </div>
    </div>
</div>

WebAppCreditos/Views/BienesSolicitante/Index.cshtml
@using Modelo.Entidades

@model IEnumerable<BienesSolicitante>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Lista Bienes Solicitante</h1>
<p> A continución se presenta la lista de los Bienes Solicitante del Sistema de Aprovación de Créditos BIESS</p>

<div class="container">
    <div class="row">
        <div class="col-sm-6">
            <h3>Bienes Solicitante</h3>
        </div>
        <div class="col-sm-6">
            <a class="btn btn-success d-block" asp-controller="BienesSolicitante" asp-action="Create">
                Nuevo Bienes Solicitante
            </a>
        </div>
    </div>
    @if (TempData["mensaje"] != null)
    {
        <div class="alert alert-warning alert-dismissible fade show " role="alert">
            @TempData["mensaje"]
            <button type="button" class="close" data-dismiss="alert" aria-label="close">
                <span ariaaria-hidden="true">
                    &times;
                </span>
            </button>
        </div>
    }
    <div class="row">
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Automovil</th>
                    <th>Pago Automovil</th>
                    <th>Casa</th>
                    <th>Pago Casa</th>
                    <th>Terreno</th>
                    <th>Pago Terreno</th>
                    <th>Total Pendiente</th>
                    <th>Solicitante</th>
                </tr>
            </thead>
            <tbody>
                @foreach (BienesSolicitante bienesSol in Model)
                {
                    <tr>
                        <td>@bienesSol.BienesSolicitanteId</td>
                        <td>@bienesSol.Automovil</td>
                        <td>@bienesSol.PagoPendienteAutomovil</td>
                        <td>@bienesSol.Casa</td>
                        <td>@bienesSol.PagoPendienteCasa</td>
                        <td>@bienesSol.Terreno</td>
                        <td>@bienesSol.PagoPendienteTerreno</td>
                        <td>@bienesSol.TotalPendienteBienes</td>
                        <td>@bienesSol.Solicitante.Nombres @bienesSol.Solicitante.Apellidos</td>
                        <td>
                            <a class="btn btn-warning" asp-controller="BienesSolicitante" asp-action="Edit" asp-route-id="@bienesSol.BienesSolicitanteId"> Editar </a>
                            <a class="btn btn-danger" asp-controller="BienesSolicitante" asp-action="Delete" asp-route-id="@bienesSol.BienesSolicitanteId"> Eliminar </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
