WebAppCreditos/Controllers/AfiliadosController.cs
using Microsoft.AspNetCore.Mvc;
using Modelo.Entidades;
using ModeloDB;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace WebAppCreditos.Controllers
{
    public class AfiliadosController : Controller
    {
        private readonly DBCreditos db;

        public AfiliadosController(DBCreditos db)
        {
            this.db = db;
        }

        //Listar Afiliados
        public IActionResult Index()
        {
            IEnumerable<Afiliado> listaAfiliados = db.Afiliado
                .Include(afiliado => afiliado.Solicitante);

            return View(listaAfiliados);
        }

        [HttpGet]
        public IActionResult Create()
        {
            // Lista de Solicitantes
            var listaSoli = db.Solicitantes
                .Select(Soli => new
                {
                    SolicitanteId = Soli.SolicitanteId,
                    Nombres = Soli.Nombres, 
                    Apellidos = Soli.Apellidos
                }).ToList();

            // Prepara las listas
            var selectListaSolicitantes = new SelectList(listaSoli, "SolicitanteId", "Nombres", "Apellidos");

            // Ingreso a ViewBag
            ViewBag.selectListSolicitantes = selectListaSolicitantes;

            return View();
        }


        [HttpPost]
        public IActionResult Create(Afiliado afiliado)
        {
            //Se obtiene el número de aportes al IESS
            afiliado.TotalAportaciones = (((afiliado.PeriodoHasta - afiliado.PeriodoDesde).Days)*12)/365;
        
            db.Afiliado.Add(afiliado);
            db.SaveChanges();

            TempData["mensaje"] = $"El afiliado de la empresa {afiliado.NombreEmpresa} se ha creado correctamente";

            return RedirectToAction("Index");
        }

        //Edicion de Afiliado
        //Presenta el formulario lleno con los datos del Afiliado seleccionada
        [HttpGet]
        public IActionResult Edit(int id)
        {
            // Lista de Solicitantes
            var listaSoli = db.Solicitantes
                .Select(Soli => new
                {
                    SolicitanteId = Soli.SolicitanteId,
                    Nombres = Soli.Nombres,
                    Apellidos = Soli.Apellidos
                }).ToList();

            // Prepara las listas
            var selectListaSolicitantes = new SelectList(listaSoli, "SolicitanteId", "Nombres", "Apellidos");

            // Ingreso a ViewBag
            ViewBag.selectListSolicitantes = selectListaSolicitantes;

            var afiliado = db.Afiliado
                .Include(soli =>soli.Solicitante)
                .Single(afili => afili.AfiliadoId == id);

            return View(afiliado);
        }

        //Actualiza Solicitante
        [HttpPost]
        public IActionResult Edit(Afiliado afiliado)
        {
            //Se obtiene el número de aportes al IESS
            afiliado.TotalAportaciones = (((afiliado.PeriodoHasta - afiliado.PeriodoDesde).Days) * 12) / 365;

            db.Afiliado.Update(afiliado);
            db.SaveChanges();

            TempData["mensaje"] = $"El afiliado de la empresa {afiliado.NombreEmpresa} se ha editado correctamente";

            return RedirectToAction("Index");
        }

        //Eliminar Afiliado
        //Presenta el formulario lleno con los datos del afiliado seleccionado
        [HttpGet]
        public IActionResult Delete(int id)
        {
            // Lista de Solicitantes
            var listaSoli = db.Solicitantes
                .Select(Soli => new
                {
                    SolicitanteId = Soli.SolicitanteId,
                    Nombres = Soli.Nombres,
                    Apellidos = Soli.Apellidos
                }).ToList();

            // Prepara las listas
            var selectListaSolicitantes = new SelectList(listaSoli, "SolicitanteId", "Nombres", "Apellidos");

            // Ingreso a ViewBag
            ViewBag.selectListSolicitantes = selectListaSolicitantes;

            var afiliado = db.Afiliado
               .Include(soli => soli.Solicitante)
               .Single(afili => afili.AfiliadoId == id);

            return View(afiliado);
        }

        //Confirmar eliminacion
        [HttpPost]
        public IActionResult Delete(Afiliado afiliado)
        {
            db.Afiliado.Remove(afiliado);
            db.SaveChanges();

            TempData["mensaje"] = $"El afiliado se ha eliminado correctamente";

            return RedirectToAction("Index");
        }
    }
}

WebAppCreditos/Controllers/GastosController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Modelo.Entidades;
using ModeloDB;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebAppCreditos.Controllers
{
    public class GastosController : Controller
    {
        private readonly DBCreditos db;

        public GastosController(DBCreditos db)
        {
            this.db = db;
        }

        //Listar Afiliados
        public IActionResult Index()
        {
            IEnumerable<Gastos> listaGastos = db.Gastos
                .Include(afiliado => afiliado.Solicitante);

            return View(listaGastos);
        }

        [HttpGet]
        public IActionResult Create()
        {
            // Lista de Solicitantes
            var listaSoli = db.Solicitantes
                .Select(Soli => new
                {
                    SolicitanteId = Soli.SolicitanteId,
                    Nombres = Soli.Nombres,
                    Apellidos = Soli.Apellidos
                }).ToList();

            // Prepara las listas
            var selectListaSolicitantes = new SelectList(listaSoli, "SolicitanteId", "Nombres", "Apellidos");

            // Ingreso a ViewBag
            ViewBag.selectListSolicitantes = selectListaSolicitantes;

            return View();
        }

        [HttpPost]
        public IActionResult Create(Gastos gastos)
        {
            //Calculo gastos Totales
            gastos.TotalGastos = gastos.Arriendo + gastos.ServiciosBasicos + gastos.Comida + gastos.Transporte + gastos.Educacion + gastos.GastosVarios;

            db.Gastos.Add(gastos);
            db.SaveChanges();

            TempData["mensaje"] = $"Los gastos del solicitante {gastos.SolicitanteId} se ha creado correctamente";

            return RedirectToAction("Index");
        }

        //Edicion de Detalle
        //Presenta el formulario lleno con los datos del detalle
        [HttpGet]
        public IActionResult Edit(int id)
        {
            // Lista de Solicitantes
            var listaSoli = db.Solicitantes
                .Select(Soli => new
                {
                    SolicitanteId = Soli.SolicitanteId,
                    Nombres = Soli.Nombres,
                    Apellidos = Soli.Apellidos
                }).ToList();

            // Prepara las listas
            var selectListaSolicitantes = new SelectList(listaSoli, "SolicitanteId", "Nombres", "Apellidos");

            // Ingreso a ViewBag
            ViewBag.selectListSolicitantes = selectListaSolicitantes;

            var gastos = db.Gastos
               .Include(soli => soli.Solicitante)
               .Single(afili => afili.GastosId == id);

            return View(gastos);
        }

        //Actualiza DetalleDeudas
        [HttpPost]
        public IActionResult Edit(Gastos gastos)
        {
            //Calculo gastos Totales
            gastos.TotalGastos = gastos.Arriendo + gastos.ServiciosBasicos + gastos.Comida + gastos.Transporte + gastos.Educacion + gastos.GastosVarios;

            db.Gastos.Update(gastos);
            db.SaveChanges();

            TempData["mensaje"] = $"Los gastos del solicitante {gastos.SolicitanteId} se ha editada correctamente";

            return RedirectToAction("Index");
        }

        //Eliminar Detalle deudas
        //Presenta el formulario lleno con los datos del detalle deudas
        [HttpGet]
        public IActionResult Delete(int id)
        {
            // Lista de Solicitantes
            var listaSoli = db.Solicitantes
                .Select(Soli => new
                {
                    SolicitanteId = Soli.SolicitanteId,
                    Nombres = Soli.Nombres,
                    Apellidos = Soli.Apellidos
                }).ToList();

            // Prepara las listas
            var selectListaSolicitantes = new SelectList(listaSoli, "SolicitanteId", "Nombres", "Apellidos");

            // Ingreso a ViewBag
            ViewBag.selectListSolicitantes = selectListaSolicitantes;

            var gastos = db.Gastos
               .Include(soli => soli.Solicitante)
               .Single(afili => afili.GastosId == id);

            return View(gastos);
        }

        //Confirmar eliminacion
        [HttpPost]
        public IActionResult Delete(Gastos gastos)
        {
            db.Gastos.Remove(gastos);
            db.SaveChanges();

            TempData["mensaje"] = $"El afiliado se ha eliminado correctamente";

            return RedirectToAction("Index");
        }
    }
}

WebAppCreditos/Controllers/RolPagosController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Modelo.Entidades;
using ModeloDB;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebAppCreditos.Controllers
{
    public class RolPagosController : Controller
    {
        private readonly DBCreditos db;

        public RolPagosController(DBCreditos db)
        {
            this.db = db;
        }

        //Listar Rol Pagos
        public IActionResult Index()
        {
            IEnumerable<RolPagos> listaRolPagos = db.RolPagos
                .Include(afiliado => afiliado.Solicitante);

            return View(listaRolPagos);
        }

        [HttpGet]
        public IActionResult Create()
        {
            // Lista de Solicitantes
            var listaSoli = db.Solicitantes
                .Select(Soli => new
                {
                    SolicitanteId = Soli.SolicitanteId,
                    Nombres = Soli.Nombres,
                    Apellidos = Soli.Apellidos
                }).ToList();

            // Prepara las listas
            var selectListaSolicitantes = new SelectList(listaSoli, "SolicitanteId", "Nombres", "Apellidos");

            // Ingreso a ViewBag
            ViewBag.selectListSolicitantes = selectListaSolicitantes;

            return View();
        }

        [HttpPost]
        public IActionResult Create(RolPagos rol)
        {
            //Calculo Total Ingresos
            rol.AporteIESS = rol.Sueldo - (rol.Sueldo * 0.945f);
            rol.TotalIngresos = rol.Sueldo - (rol.AporteIESS + rol.PrestamosIESS + rol.Anticipo);

            db.RolPagos.Add(rol);
            db.SaveChanges();

            TempData["mensaje"] = $"E Rol de pagos del solicitante {rol.SolicitanteId} se ha creado correctamente";

            return RedirectToAction("Index");
        }

        //Edicion de Rol Pagos
        //Presenta el formulario lleno con los datos del RolPagos
        [HttpGet]
        public IActionResult Edit(int id)
        {
            // Lista de Solicitantes
            var listaSoli = db.Solicitantes
                .Select(Soli => new
                {
                    SolicitanteId = Soli.SolicitanteId,
                    Nombres = Soli.Nombres,
                    Apellidos = Soli.Apellidos
                }).ToList();

            // Prepara las listas
            var selectListaSolicitantes = new SelectList(listaSoli, "SolicitanteId", "Nombres", "Apellidos");

            // Ingreso a ViewBag
            ViewBag.selectListSolicitantes = selectListaSolicitantes;

            var rol = db.RolPagos
               .Include(soli => soli.Solicitante)
               .Single(afili => afili.RolPagosId == id);

            return View(rol);
        }

        //Actualiza DetalleDeudas
        [HttpPost]
        public IActionResult Edit(RolPagos rol)
        {
            //Calculo Total Ingresos
            rol.AporteIESS = rol.Sueldo - rol.Sueldo * 0.945f;
            rol.TotalIngresos = rol.Sueldo - (rol.AporteIESS + rol.PrestamosIESS + rol.Anticipo);

            db.RolPagos.Update(rol);
            db.SaveChanges();

            TempData["mensaje"] = $"El Rol de Pagos del solicitante {rol.SolicitanteId} se ha editada correctamente";

            return RedirectToAction("Index");
        }

        //Eliminar Detalle deudas
        //Presenta el formulario lleno con los datos del detalle deudas
        [HttpGet]
        public IActionResult Delete(int id)
        {
            // Lista de Solicitantes
            var listaSoli = db.Solicitantes
                .Select(Soli => new
                {
                    SolicitanteId = Soli.SolicitanteId,
                    Nombres = Soli.Nombres,
                    Apellidos = Soli.Apellidos
                }).ToList();

            // Prepara las listas
            var selectListaSolicitantes = new SelectList(listaSoli, "SolicitanteId", "Nombres", "Apellidos");

            // Ingreso a ViewBag
            ViewBag.selectListSolicitantes = selectListaSolicitantes;

            var rol = db.RolPagos
               .Include(soli => soli.Solicitante)
               .Single(afili => afili.RolPagosId == id);

            return View(rol);
        }

        //Confirmar eliminacion
        [HttpPost]
        public IActionResult Delete(RolPagos rol)
        {
            db.RolPagos.Remove(rol);
            db.SaveChanges();

            TempData["mensaje"] = $"El afiliado se ha eliminado correctamente";

            return RedirectToAction("Index");
        }
    }
}

WebAppCreditos/Controllers/SolicitanteController.cs
using Microsoft.AspNetCore.Mvc;
using Modelo.Entidades;
using ModeloDB;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebAppCreditos.Controllers
{
    public class SolicitanteController : Controller
    {
        private readonly DBCreditos db;

        public SolicitanteController(DBCreditos db)
        {
            this.db = db;
        }

        //Listar Rol Pagos
        public IActionResult Index()
        {
            IEnumerable<Solicitante> listaSolicitante = db.Solicitantes;

            return View(listaSolicitante);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        //Creamos Solicitante
        [HttpPost]
        public IActionResult Create(Solicitante solicitante)
        {
            db.Solicitantes.Add(solicitante);
            db.SaveChanges();

            TempData["mensaje"] = $"El registro ha sido ingresado correctamente exitosamente";

            return RedirectToAction("Index");
        }

        //Edicion de Solicitante
        //Presenta el formulario lleno con los datos del solicitante seleccionada
        [HttpGet]
        public IActionResult Edit(int id)
        {
            Solicitante solicitante = db.Solicitantes.Find(id);

            return View(solicitante);
        }

        //Actualiza Solicitante
        [HttpPost]
        public IActionResult Edit(Solicitante solicitante)
        {
            db.Solicitantes.Update(solicitante);
            db.SaveChanges();

            TempData["mensaje"] = $"El Solicitante {solicitante.Nombres} {solicitante.Apellidos} ha sido actualizada exitosamente";

            return RedirectToAction("Index");
        }

        //Eliminar Solicitante
        //Presenta el formulario lleno con los datos del solicitante seleccionada
        [HttpGet]
        public IActionResult Delete(int id)
        {
            Solicitante solicitante = db.Solicitantes.Find(id);

            return View(solicitante);
        }

        //Confirmar eliminacion
        [HttpPost]
        public IActionResult Delete(Solicitante solicitante)
        {
            db.Solicitantes.Remove(solicitante);
            db.SaveChanges();

            TempData["mensaje"] = $"El Solicitante ha sido eliminado exitosamente";

            return RedirectToAction("Index");
        }
    }
}

WebAppCreditos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebAppCreditos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light  bg-primary">
            <div class="container-fluid">
                <h1 class="navbar-brand text-light" href="#" >BIESS</h1>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse " id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active text-light" aria-current="page" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" aria-current="page" href="#">Información</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-light" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Tipo de Créditos
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="#">Vivienda Terminada</a></li>
                                <li><a class="dropdown-item" href="#">Vivienda de Intéres Público</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" href="#">Otros Bienes Inmuebles</a></li>
                            </ul>
                        </li>
                    </ul>

                    <button class="btn btn-light" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasRight" aria-controls="offcanvasRight">Clases</button>

                </div>
            </div>
        </nav>
        <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasRight" aria-labelledby="offcanvasRightLabel">
            <div class="offcanvas-header">
                <h5 id="offcanvasRightLabel">Clases Crédito</h5>
                <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
            </div>
            <div class="offcanvas-body">
                <ul class="list-group">
                    <li class="list-group-item">
                        <a class="dropdown-item" asp-area="" asp-controller="Solicitante" asp-action="Index">Solicitante</a>
                    </li>
                    <li class="list-group-item">
                        <a class="dropdown-item" asp-area="" asp-controller="Afiliados" asp-action="Index">Afiliados</a>
                    </li>
                    <li class="list-group-item">
                        <a class="dropdown-item" asp-area="" asp-controller="BienAdquirir" asp-action="Index">Bien Adquirir</a>
                    </li>
                    <li class="list-group-item">
                        <a class="dropdown-item" asp-area="" asp-controller="RolPagos" asp-action="Index">Rol de Pagos</a>
                    </li>
                    <li class="list-group-item">
                        <a class="dropdown-item" asp-area="" asp-controller="DeclaracionImp" asp-action="Index">Declaracion Impuestos</a>
                    </li>
                    <li class="list-group-item">
                        <a class="dropdown-item" asp-area="" asp-controller="Gastos" asp-action="Index"> Gastos </a>
                    </li>
                    <li class="list-group-item">
                        <a class="dropdown-item" asp-area="" asp-controller="CapacidadPagos" asp-action="Index"> Capacidad Pagos</a>
                    </li>
                    <li class="list-group-item">
                        <a class="dropdown-item" asp-area="" asp-controller="BienesSolicitante" asp-action="Index"> Bienes Solicitante</a>
                    </li>
                    <li class="list-group-item">
                        <a class="dropdown-item" asp-area="" asp-controller="DetalleDeudas" asp-action="Index">Detalle Deudas</a>
                    </li>
                    <li class="list-group-item">
                        <a class="dropdown-item" asp-area="" asp-controller="HistorialCrediticio" asp-action="Index">Historial Crediticio</a>
                    </li>
                    <li class="list-group-item">
                        <a class="dropdown-item" asp-area="" asp-controller="Solicitud" asp-action="Index"> Solicitud</a>
                    </li>
                    <li class="list-group-item">
                        <a class="dropdown-item" asp-area="" asp-controller="Solicitud_Det" asp-action="Index">Solicitud Detalle</a>
                    </li>
                    <li class="list-group-item">
                        <a class="dropdown-item" asp-area="" asp-controller="Amortizacion" asp-action="Index">Amortizacion</a>
                    </li>
                </ul>
            </div>
        </div>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-center">
            &copy; 2022 - Anthony Rosero & Elkin Romero - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>